### ISSUE TITLE
depslint crashes when run on a chromium build

### ISSUE THREAD

**Issue by nico** [maximuska/depslint#2]
I tried running depslint on a chromium linux build. About halfway through, it died. This is the output:

```
thakis@yearofthelinuxdesktop:/usr/local/google/chrome/src$ ../../depslint/depstrace.py -- ninja -C out2/Release chrome
INFO: Tracing: ['ninja', '-C', 'out2/Release', 'chrome']
ninja: Entering directory `out2/Release'
[5730/12290] CXX obj/third_party/WebKit/Source/core/svg/webcore_svg.SVGStyleElement.o[ Process PID=21324 runs in 32 bit mode. ]
[ Process PID=21309 runs in 64 bit mode. ]
[ Process PID=21324 runs in 32 bit mode. ]
[ Process PID=21312 runs in 64 bit mode. ]
[ Process PID=21324 runs in 32 bit mode. ]
[ Process PID=21309 runs in 64 bit mode. ]
[ Process PID=21324 runs in 32 bit mode. ]
[ Process PID=21312 runs in 64 bit mode. ]
[ Process PID=21324 runs in 32 bit mode. ]
[ Process PID=21312 runs in 64 bit mode. ]
[ Process PID=21324 runs in 32 bit mode. ]
[ Process PID=21316 runs in 64 bit mode. ]
[ Process PID=21324 runs in 32 bit mode. ]
[ Process PID=21312 runs in 64 bit mode. ]
[ Process PID=21324 runs in 32 bit mode. ]
[ Process PID=21316 runs in 64 bit mode. ]
[ Process PID=21324 runs in 32 bit mode. ]
[ Process PID=21312 runs in 64 bit mode. ]
[ Process PID=21324 runs in 32 bit mode. ]
[ Process PID=21312 runs in 64 bit mode. ]
[ Process PID=21324 runs in 32 bit mode. ]
[ Process PID=21312 runs in 64 bit mode. ]
[ Process PID=21324 runs in 32 bit mode. ]
[ Process PID=21316 runs in 64 bit mode. ]
[ Process PID=21324 runs in 32 bit mode. ]
[ Process PID=21316 runs in 64 bit mode. ]
[ Process PID=21324 runs in 32 bit mode. ]
[ Process PID=21316 runs in 64 bit mode. ]
[ Process PID=21324 runs in 32 bit mode. ]
[ Process PID=21316 runs in 64 bit mode. ]
[ Process PID=21324 runs in 32 bit mode. ]
[ Process PID=21316 runs in 64 bit mode. ]
[ Process PID=21324 runs in 32 bit mode. ]
[ Process PID=21316 runs in 64 bit mode. ]
Traceback (most recent call last):
  File "../../depslint/depstrace.py", line 354, in <module>
    ret = tracecmd(options, args)
  File "../../depslint/depstrace.py", line 309, in tracecmd
    status, rules = tracer.trace(cmd=args)
  File "../../depslint/depstrace.py", line 185, in trace
    rules = self.parse_trace(file(fifopath))
  File "../../depslint/depstrace.py", line 213, in parse_trace
    for pid, op, ret, arg1, arg2 in log_iterator:
  File "../../depslint/depstrace.py", line 274, in _strace_log_iter
    line = interrupted_syscalls[pid] + body
KeyError: '21316'
[ Process PID=21324 runs in 32 bit mode. ]
[ Process PID=21322 runs in 64 bit mode. ]
```

(Not sure if you care about bug reports, feel free to close this if not :-) If you are interested in bug reports, I'm happy to provide whatever other data you might need to debug this.)

**Comment by maximuska** [comment]
Yeah.. a pull request could be better.

That means it matched a PID xxx 'resumed' line in strace output w/o remembering to ever see a matching 'PID: xxx( <unfinished' before.
Can you please paste the output of 'grep ^21316 strace_log.txt'?

**Comment by maximuska** [comment]
Other option, and if this looks really weird, I please re-run build under strace outside the tool to collect 'strace_out.txt'.

You can run the tool with '-v', to take a note of strace command line yo should use, then kill the script and rerun the build under strace manually.

**Comment by nico** [comment]
I've attached the output of `grep ^21316 strace_log.txt` to https://code.google.com/p/chromium/issues/detail?id=242684#c1 (gzipped, since it's 1.4MB uncompressed).

**Comment by maximuska** [comment]
It appears to be a bug/race condition in 'strace':
    21316 open("/usr/include/directfb/streambuf", O_RDONLY|O_NOCTTY <unfinished ...>
    21316 <... open resumed> ) = -1 ENOENT (No such file or directory)
    21316 open("/usr/include/libpng12/streambuf", O_RDONLY|O_NOCTTY <unfinished ...>
    21316 <... open resumed> ) = -1 ENOENT (No such file or directory)
    21316 open("/usr/include/c++/4.4/streambuf", O_RDONLY|O_NOCTTY <unfinished ...>
    21316 <... open resumed> ) = 4
    21316 <... open resumed> ) = 0
the last <open resumed> doesn't have a preceding "open unfinished" statement. We could hunt the problem further by looking at the relevant range in the log (starting from the last unfinished open for pid 21316).

But it will be easier to first trying to upgrade to the latest strace version first and see if it still has this issue.
Another quick option could trying to limit ninja's processes in parallel to easy on strace.
Lastly Marc-Antoine offered to merging in trace_inputs frmework, which used strace in -ff mode which worked more reliably and was successfully used to trace multiple  chromium tests according to his comment, but this is a long shot.

I am curious to know how it works if you decide to invest more energy into it.

**Comment by maximuska** [comment]
Also, pushed 816b3ec558b599a75b255e4ec66e142116a91469 to handle the situation more gracefully..
